### ISSUE TITLE
Unsubscribe not working

### ISSUE THREAD

**Issue by gozeon** [Clivern/Beaver#52]
**Describe the bug**
the client get channel message after  unsubscribe this channel 

**Development or production environment**
 https://github.com/Clivern/Beaver/releases/download/1.1.1/Beaver_1.1.1_Linux_x86_64.tar.gz

**Comment by Clivern** [comment]
Can you please share the steps you do or API Calls? since i already checked and works fine and message not delivered in case client unsubscribed from a channel.

**Comment by Clivern** [comment]
Actually the backend should be the one responsible for these calls (All calls with api key since this can not be on frontend side). 
- The backend create a channel, create a client and subscribe that client to a channel(s). 
- It returns the id and token to on frontend for clients to connect.
- anytime backend can do any action even deleting the client. it will not be able to get messages anymore.
