### ISSUE TITLE
I have some questions about this library

### ISSUE THREAD

**Issue by mghifariyusuf** [Clivern/Beaver#76]
Hi @Clivern 
First, I appreciate you for making this library.
But sorry to say if I still didn't understand your documentation.

Is there a 'good' documentation about it like some documentations in GoDoc or documentation provided with image for better illustrating?

Second, do you have sample or demo app?

Thankyou in advance 🙏🏼

**Comment by Clivern** [comment]
Hi @mghifariy,

The documentations is mainly explaining the REST endpoints and how to open js websocket to beaver, send and receive messages. 
GoDoc is not reqquired in these cases since it is not sdk, it a complete solution that you need to build your stuff around but i totally agree that having a working example would be nice. 

I created this task before https://github.com/Clivern/Beaver/issues/30 but i didn't find time to work on it. but i will try

Thanks!
